////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

[id='connecting-other-routers-{context}']
= Connecting with other routers

If the router is operating in interior mode, you can connect it to other routers to form a router network. To connect to another router, you add an inter-router _connector_.

AMQP connections are bidirectional. To connect two routers, you only need to create a connector on one of the routers. After the connection is established, both routers can communicate over the connection.

// TODO: explain how to decide which direction to make the connection (i.e. more private to more public)

.Procedure

. Verify that the router to which you want to connect has an inter-router listener.
+
--
If necessary, create a listener that can accept inter-router connections.

[options="nowrap",subs="+quotes"]
----
listener {
    host: __<host_name_or_address>__
    port: __<port_number_or_name>__
    role: inter-router
    ...
}
----

`host`:: The host name or IP address (IPv4 or IPv6) on which the router should listen for inter-router connections. You can:
+
** Specify a literal host name or IP address
** Leave the value blank to listen on all local addresses
** Use the `[::]` wildcard to listen on all local IPv6 addresses
** Use the `0.0.0.0` wildcard to listen on all local IPv4 addresses

`port`:: The port number or symbolic service name on which the router should listen for incoming inter-router connections.

`role`:: Enter `inter-router`. This value means that this listener can only accept connections from other routers in the network for inter-router discovery and routing protocols.

To configure advanced attributes, see link:{qdrouterdConfManPageUrl}#_listener[listener^] in the qdrouterd.conf man page.
--

. On the router from which you want to create the connection, create a connector.
+
--
[options="nowrap",subs="+quotes"]
----
connector {
    host: __<host_name_or_address>__
    port: __<port_number_or_name>__
    role: inter-router
    ...
}
----

`host`:: The IP address (IPv4 or IPv6) or host name to which the router should connect. The router to which you want to connect must have an inter-router listener listening on this host.

`port`:: The port number or symbolic service name tn which the router should connect. The router to which you want to connect must have an inter-router listener listening on this port.

`role`:: Enter `inter-router`. This value means that this connector can only connect to other routers in the network.

To configure advanced attributes, see link:{qdrouterdConfManPageUrl}#_connector[connector^] in the qdrouterd.conf man page.
--

. If you want to connect this router to any other routers, repeat this procedure for each connection.

// .Additional resources

// * xref:securing-inter-router-connections-router[]
