////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

[id='understanding-router-configuration-file-{context}']
= Understanding the router configuration file

To configure the router, you must edit the router configuration file (`qdrouterd.conf`). Therefore, you should know where the file is located, and how it is structured.

By default, `qdrouterd.conf` is located at `/etc/qpid-dispatch/qdrouterd.conf`.

The configuration file contains sections. A section is a configurable entity, and it contains a set of attribute name-value pairs that define the settings for that entity. The syntax is as follows:

[options="nowrap"]
----
sectionName {
    attributeName: attributeValue
    attributeName: attributeValue
    ...
}
----

.Additional resources

* {qdrouterdConfManPageLink}
