////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// book.adoc

[id='deploying-router-{context}']
= Deploying a router

To deploy a router, you must install {RouterName} on a host, configure it to meet your requirements, and then start the router.

.Prerequisites

* {RouterName} must be installed on the host on which you want to deploy the router.
+
For more information, see xref:installing-router-router[].

// Planning


// Preparing to deploy the router


// Configuring the router
include::configuring-router.adoc[leveloffset=+1]

// Starting the router


// Adding additional routers

